export const CONSOLES = [
  {
    gamesdb_id: 18,
    screenscrapper_id: 1,
    name: "sega genesis/mega drive",
    extensions: ["zip", "7z", "gen", "md", "smd", "bin", "sg"],
    foldernames: [
      "megadrive",
      "genesis",
      "megadrivejp",
      "md",
      "sega genesis (md)",
      "sega genesis",
      "sega megadrive",
      "super aladdin boy",
      "msumd",
    ],
    icon: "/consoles/megadrive2.png",
  },
  {
    screenscrapper_id: 2,
    gamesdb_id: 35,
    name: "sega master system",
    extensions: ["zip", "7z", "sms", "bin"],
    foldernames: [
      "master system",
      "mastersystem",
      "sega master system",
      "sega mark iii",
      "sega mark 3",
      "ms",
      "sega master system (sms)",
      "sms",
    ],
    icon: "/consoles/sms.png",
  },
  {
    screenscrapper_id: 3,
    gamesdb_id: 7,
    name: "nes",
    extensions: ["zip", "7z", "nes", "fds", "fig", "bin", "unf"],
    foldernames: [
      "nes",
      "family computer",
      "nintendo entertainment system",
      "nintendo famicom",
      "fc",
      "nintendo entertainment system (fc)",
      "famicom",
      "nintendo family computer",
    ],
    icon: "/consoles/nes.png",
  },
  {
    screenscrapper_id: 4,
    gamesdb_id: 6,
    name: "super nintendo",
    extensions: ["zip", "7z", "sfc", "smc", "fig", "mgd", "swc"],
    foldernames: [
      "super nintendo",
      "super famicom",
      "snes",
      "snesna",
      "sfc",
      "super nintendo entertainment system (sfc)",
      "super nintendo entertainment system (supa)",
      "super nintendo entertainment system",
      "nintendo super famicom",
    ],
    icon: "/consoles/snes.png",
  },
  {
    screenscrapper_id: 6,
    name: "capcom play system",
    extensions: ["zip", "7z", "chd"],
    foldernames: [
      "capcom play system",
      "arcade",
      "mame",
      "fba",
      "fba_libretro",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "capcom play system 1",
      "capcom play system i",
      "cps 1",
      "cps",
      "cps i",
      "cps1",
    ],
    icon: "/consoles/cps.png",
  },
  {
    screenscrapper_id: 7,
    name: "capcom play system ii",
    extensions: ["zip", "7z", "chd"],
    foldernames: [
      "capcom play system 2",
      "arcade",
      "mame",
      "fba",
      "fba_libretro",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "capcom play system ii",
      "cps 2",
      "cps ii",
      "cps2",
    ],
    icon: "/consoles/cps.png",
  },
  {
    screenscrapper_id: 8,
    name: "capcom play system iii",
    extensions: ["zip", "7z", "ccd", "chd", "img", "sub"],
    foldernames: [
      "capcom play system 3",
      "arcade",
      "mame",
      "cps3",
      "fba",
      "fba_libretro",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "capcom play system iii",
      "cps 3",
      "cps iii",
    ],
    icon: "/consoles/cps.png",
  },
  {
    screenscrapper_id: 9,
    gamesdb_id: 4,
    name: "nintendo game boy",
    extensions: ["zip", "7z", "gb", "bin"],
    foldernames: [
      "game boy",
      "gb",
      "nintendo game boy",
      "nintendo gb",
      "game boy (gb)",
    ],
    icon: "/consoles/gb_dmg.png",
  },
  {
    gamesdb_id: 41,
    screenscrapper_id: 10,
    name: "nintendo game boy color",
    parentid: 9,
    extensions: ["zip", "7z", "gb", "gbc", "bin"],
    foldernames: [
      "game boy color",
      "gbc",
      "game boy color (gbc)",
      "nintendo game boy color",
      "nintendo gb color",
      "nintendo gbc",
      "gb color",
    ],
    icon: "/consoles/gbc_yellow.png",
  },
  {
    gamesdb_id: 4918,
    screenscrapper_id: 11,
    name: "nintendo virtual boy",
    extensions: ["zip", "7z", "vb", "vboy", "bin"],
    foldernames: [
      "virtual boy",
      "nintendo virtual boy",
      "nintendo virtualboy",
      "virtualboy",
      "nintendo vboy",
      "vboy",
      "vb",
      "virtual boy (vb)",
    ],
    icon: "/consoles/virtualboy.png",
  },
  {
    screenscrapper_id: 12,
    gamesdb_id: 5,
    name: "nintendo game boy advance",
    extensions: ["zip", "7z", "gba", "bin"],
    foldernames: [
      "game boy advance",
      "gba",
      "game boy advance (gba)",
      "game boy advance (mgba)",
      "nintendo game boy advance",
      "nintendo gameboy advance",
      "gameboy advance",
      "nintendo gb advance",
      "nintendo gba",
      "gb advance",
    ],
    icon: "/consoles/gba.png",
  },
  {
    name: "nintendo gamecube",
    gamesdb_id: 2,
    screenscrapper_id: 13,
    extensions: ["zip", "7z", "iso", "gcz"],
    foldernames: [
      "gamecube",
      "gc",
      "nintendo gamecube",
      "nintendo game cube",
      "game cube",
      "nintendo gc",
      "ngc",
    ],
    icon: "/consoles/ngc_orange01.png",
  },
  {
    gamesdb_id: 3,
    screenscrapper_id: 14,
    name: "nintendo 64",
    extensions: ["zip", "7z", "n64", "v64", "z64"],
    foldernames: ["nintendo 64", "n64", "nintendo 64 (n64)"],
    icon: "/consoles/n64.png",
  },
  {
    screenscrapper_id: 15,
    gamesdb_id: 8,
    name: "nintendo ds",
    extensions: ["zip", "7z", "nds", "bin"],
    foldernames: [
      "nintendo ds",
      "nds",
      "ds",
      "nintendo dsi",
      "ndsi",
      "nintendo ds (nds)",
      "dsi",
    ],
    icon: "/consoles/nintendodsi04b.png",
  },
  {
    screenscrapper_id: 16,
    gamesdb_id: 9,
    name: "nintendo wii",
    extensions: ["zip", "7z", "iso", "ciso", "wad", "wbfs"],
    foldernames: ["wii", "nintendo wii"],
    icon: "/consoles/wii.png",
  },
  {
    gamesdb_id: 4912,
    screenscrapper_id: 17,
    extensions: ["zip", "7z", "3ds"],
    name: "nintendo 3ds",
    foldernames: ["nintendo 3ds", "3ds", "2ds", "n3ds"],
    icon: "/consoles/nintendo3ds_c01.png",
  },
  {
    screenscrapper_id: 18,
    gamesdb_id: 38,
    name: "nintendo wii u",
    extensions: ["zip", "7z", "iso", "ciso", "wbfs"],
    foldernames: ["wii u", "wiiu", "nintendo wii u", "nintendo wii-u", "wii-u"],
    icon: "/consoles/wiiu.png",
  },
  {
    gamesdb_id: 33,
    screenscrapper_id: 19,
    parentid: 1,
    name: "sega 32x",
    extensions: [
      "zip",
      "7z",
      "32x",
      "smd",
      "md",
      "bin",
      "ccd",
      "cue",
      "img",
      "iso",
      "sub",
      "wav",
    ],
    foldernames: [
      "megadrive 32x",
      "sega 32x",
      "sega32x",
      "sega32xjp",
      "sega32xna",
      "sega megadrive 32x",
      "sega genesis 32x",
      "sega mega 32x",
      "super 32x",
      "genesis 32x",
      "32x",
      "thirtytwox",
    ],
    icon: "/consoles/md_super32x02.png",
  },
  {
    gamesdb_id: 21,
    screenscrapper_id: 20,
    name: "sega cd",
    extensions: [
      "zip",
      "7z",
      "bin",
      "ccd",
      "chd",
      "cue",
      "img",
      "iso",
      "sub",
      "wav",
    ],
    foldernames: ["mega-cd", "sega cd", "megacd", "megacdjp", "segacd"],
    icon: "/consoles/megacd02.png",
  },
  {
    gamesdb_id: 20,
    screenscrapper_id: 21,
    name: "sega game gear",
    extensions: ["zip", "7z", "gg", "sms", "bin"],
    foldernames: [
      "game gear",
      "gamegear",
      "sega game gear",
      "sega gg",
      "gg",
      "sega game gear (gg)",
    ],
    icon: "/consoles/gamegear.png",
  },
  {
    screenscrapper_id: 22,
    gamesdb_id: 17,
    name: "sega saturn",
    extensions: ["zip", "7z", "chd", "cue", "bin", "mdf", "iso", "m3u"],
    foldernames: ["saturn", "sega saturn"],
    icon: "/consoles/ss_vsaturn.png",
  },
  {
    gamesdb_id: 16,
    screenscrapper_id: 23,
    name: "sega dreamcast",
    extensions: [
      "zip",
      "7z",
      "cdi",
      "chd",
      "gdi",
      "bin",
      "elf",
      "img",
      "nrg",
      "raw",
      "xpm",
      "m3u",
    ],
    foldernames: [
      "dreamcast",
      "sega dreamcast",
      "sega dreamcast (dc)",
      "sega dc",
      "dc",
    ],
    icon: "/consoles/dc3.png",
  },
  {
    gamesdb_id: 4922,
    screenscrapper_id: 25,
    parentid: 82,
    name: "snk neo geo pocket",
    extensions: ["zip", "7z", "ngp", "ngc", "bin"],
    foldernames: [
      "neo-geo pocket",
      "ngp",
      "snk neo geo pocket",
      "snk neo-geo pocket",
      "snk ngp",
      "gp",
    ],
    icon: "/consoles/neogeopocket_com.png",
  },
  {
    gamesdb_id: 22,
    screenscrapper_id: 26,
    name: "atari 2600",
    extensions: ["zip", "7z", "a26", "bin", "rom"],
    foldernames: ["atari", "atari 2600", "atari2600", "a2600", "2600"],
    icon: "/consoles/2600_darth_vader.png",
  },
  {
    gamesdb_id: 28,
    screenscrapper_id: 27,
    name: "atari jaguar",
    extensions: ["zip", "7z", "j64", "jag", "cof", "bin", "rom", "abs"],
    foldernames: ["jaguar", "atarijaguar", "atari jaguar"],
    icon: "/consoles/jaguar02.png",
  },
  {
    gamesdb_id: 4924,
    screenscrapper_id: 28,
    name: "atari lynx",
    extensions: ["zip", "7z", "bin", "lnx", "o"],
    foldernames: ["lynx", "atarilynx", "atari lynx"],
    icon: "/consoles/lynx.png",
  },
  {
    screenscrapper_id: 29,
    gamesdb_id: 25,
    extensions: ["zip", "7z", "bin", "cue", "iso", "wav", "chd"],
    name: "3do interactive multiplayer",
    foldernames: [
      "3do",
      "3do interactive multiplayer",
      "panasonic 3do",
      "panasonic 3do interactive multiplayer",
      "panasonic",
    ],
    icon: "/consoles/3do_real.png",
  },
  {
    gamesdb_id: 4938,
    name: "ngage",
    screenscrapper_id: 30,
    extensions: ["zip", "7z", "id"],
    foldernames: ["n-gage", "nokia n-gage"],
    icon: "/consoles/ngage.png",
  },
  {
    screenscrapper_id: 31,
    gamesdb_id: 34,
    name: "nec turbografx-16",
    extensions: ["zip", "7z", "pce", "sgx"],
    foldernames: [
      "pc engine",
      "turbografx-16",
      "tg16",
      "pcengine",
      "pce",
      "turbografx-16 (pce)",
      "nec turbografx-16",
      "nec pc engine",
    ],
    icon: "/consoles/turbografx01.png",
  },
  {
    gamesdb_id: 14,
    screenscrapper_id: 32,
    name: "microsoft xbox",
    extensions: ["zip", "7z", "iso"],
    foldernames: ["xbox", "microsoft xbox"],
    icon: "/consoles/xbox03.png",
  },
  {
    gamesdb_id: 15,
    screenscrapper_id: 33,
    extensions: ["zip", "7z", "iso"],
    name: "microsoft xbox 360",
    foldernames: ["xbox 360", "microsoft xbox 360"],
    icon: "/consoles/xbox360s01.png",
  },
  {
    gamesdb_id: 4920,
    name: "microsoft xbox one",
    screenscrapper_id: 34,
    extensions: ["zip", "7z", "iso"],
    foldernames: ["xbox one", "microsoft xbox one"],
    icon: "/consoles/xboxone.png",
  },
  {
    gamesdb_id: 5014,
    name: "acorn atom",
    screenscrapper_id: 36,
    extensions: ["zip", "7z", "csw", "dsk", "tap", "uef", "wav"],
    foldernames: ["atom", "acorn atom"],
    icon: "/consoles/atom.png",
  },
  {
    screenscrapper_id: 37,
    extensions: [
      "zip",
      "7z",
      "adf",
      "adl",
      "bin",
      "dsd",
      "ssd",
      "uef",
      "csw",
      "m3u",
    ],
    gamesdb_id: 5013,
    name: "acorn computers bbc micro",
    foldernames: [
      "bbc micro",
      "bbcmicro",
      "bbc microcomputer system",
      "acorn bbc micro",
      "acorn bbc microcomputer system",
    ],
    icon: "/consoles/bbc-micro.png",
  },
  {
    gamesdb_id: 26,
    screenscrapper_id: 40,
    name: "atari 5200",
    extensions: [
      "zip",
      "7z",
      "a52",
      "atr",
      "atx",
      "bin",
      "car",
      "cas",
      "cdm",
      "rom",
      "xex",
      "xfd",
    ],
    foldernames: [
      "atari 5200",
      "atari5200",
      "a5200",
      "5200",
      "fiftytwohundred",
    ],
    icon: "/consoles/5200.png",
  },
  {
    gamesdb_id: 27,
    screenscrapper_id: 41,
    name: "atari 7800 prosystem",
    extensions: ["zip", "7z", "a78", "bin", "rom"],
    foldernames: [
      "atari 7800",
      "atari7800",
      "seventyeighthundred",
      "a7800",
      "7800",
    ],
    icon: "/consoles/7800.png",
  },
  {
    gamesdb_id: 4937,
    screenscrapper_id: 42,
    name: "atari st",
    extensions: [
      "zip",
      "7z",
      "st",
      "stx",
      "ipf",
      "ctr",
      "img",
      "raw",
      "rom",
      "msa",
      "dim",
    ],
    foldernames: [
      "atari st",
      "atarist",
      "atari ste",
      "atari 520 st",
      "atari 1040 st",
      "520 st",
      "1040 st",
    ],
    icon: "/consoles/atarist.png",
  },
  {
    screenscrapper_id: 43,
    name: "atari 800",
    extensions: [
      "zip",
      "7z",
      "a52",
      "asm",
      "atr",
      "atr.gz",
      "atx",
      "bas",
      "bin",
      "car",
      "cas",
      "com",
      "dcm",
      "rom",
      "xex",
      "xfd",
      "xfd.gz",
    ],
    gamesdb_id: 4943,
    foldernames: [
      "eighthundred",
      "atari 8bit",
      "atari800",
      "atari 800",
      "atari 8-bit",
      "atari 130xe",
      "130xe",
      "atari 800xl",
      "800xl",
      "atari 800xe",
      "800xe",
      "atari 65xe",
      "65xe",
      "atari 600xl",
      "600xl",
      "atari 1200xl",
      "1200xl",
      "atari xegs",
      "xegs",
      "atari 400",
      "a800",
      "a400",
    ],
    icon: "/consoles/atari8.png",
  },
  {
    gamesdb_id: 4968,
    name: "bally astrocade",
    screenscrapper_id: 44,
    extensions: ["zip", "7z", "bin", "prg", "wav"],
    foldernames: ["astrocade", "bally astrocade"],
    icon: "/consoles/astrocade.png",
  },
  {
    gamesdb_id: 4926,
    screenscrapper_id: 45,
    name: "bandai wonderswan",
    extensions: ["zip", "7z", "ws", "wsc", "bin"],
    foldernames: [
      "wonderswan",
      "bandai wonderswan",
      "bandai wswan",
      "wswan",
      "ws",
    ],
    icon: "/consoles/wonderswan_04.png",
  },
  {
    screenscrapper_id: 46,
    name: "bandai wonderswan color",
    parentid: 45,
    extensions: ["zip", "7z", "ws", "wsc", "bin"],
    foldernames: [
      "wonderswan color",
      "wonderswancolor",
      "bandai wonderswan color",
      "bandai wswan color",
      "wswan color",
      "ws",
      "wsc",
    ],
    icon: "/consoles/wscolor01.png",
  },
  {
    gamesdb_id: 31,
    screenscrapper_id: 48,
    name: "coleco colecovision",
    extensions: ["zip", "7z", "col", "rom", "bin"],
    foldernames: ["colecovision", "coleco"],
    icon: "/consoles/col.png",
  },
  {
    screenscrapper_id: 49,
    name: "daphne arcade laserdisc emulator",
    extensions: ["zip", "7z", "daphne(m2v|ogg)"],
    foldernames: ["daphne"],
    icon: "/consoles/daphne.png",
  },
  {
    name: "turboduo",
    screenscrapper_id: 50,
    parentid: 31,
    extensions: ["zip", "7z", "pce", "sgx"],
    foldernames: [
      "coregrafx",
      "pcengine",
      "tg16",
      "nec coregrafx",
      "pc-engine duo",
      "pce duo",
    ],
    icon: "/consoles/pce_duo.png",
  },
  {
    gamesdb_id: 4950,
    screenscrapper_id: 52,
    name: "game & watch",
    extensions: ["zip", "7z", "mgw"],
    foldernames: [
      "game & watch",
      "gw",
      "gameandwatch",
      "electronic handheld games",
      "nintendo game & watch",
      "nintendo game and watch",
      "game and watch",
      "nintendo game'n'watch",
      "game'n'watch",
      "g&w",
    ],
    icon: "/consoles/gaw.png",
  },
  {
    screenscrapper_id: 53,
    name: "sammy corporation atomiswave",
    extensions: [
      "zip",
      "7z",
      "bin",
      "cdi",
      "cue",
      "dat",
      "elf",
      "gdi",
      "iso",
      "lst",
      "m3u",
    ],
    foldernames: ["atomiswave", "sammy atomiswave"],
    icon: "/consoles/atomiswave.png",
  },
  {
    screenscrapper_id: 57,
    name: "sony playstation",
    extensions: [
      "zip",
      "7z",
      "iso",
      "bin",
      "ccd",
      "cue",
      "pbp",
      "cbn",
      "img",
      "mdf",
      "m3u",
      "toc",
      "znx",
      "chd",
    ],
    gamesdb_id: 10,
    foldernames: [
      "playstation",
      "psx",
      "sony playstation",
      "sony psx",
      "sony ps one",
      "ps one",
      "sony playstation (ps)",
      "ps1",
      "ps",
    ],
    icon: "/consoles/ps01.png",
  },
  {
    gamesdb_id: 11,
    screenscrapper_id: 58,
    name: "sony playstation 2",
    extensions: ["zip", "7z", "iso", "chd", "img", "cue", "gz"],
    foldernames: [
      "playstation 2",
      "ps2",
      "sony playstation 2",
      "sony ps2",
      "sony playstation ii",
      "playstation ii",
    ],
    icon: "/consoles/ps2_07.png",
  },
  {
    gamesdb_id: 12,
    screenscrapper_id: 59,
    name: "sony playstation 3",
    extensions: ["zip", "7z", "iso"],
    foldernames: [
      "playstation 3",
      "ps3",
      "sony playstation 3",
      "sony ps3",
      "sony playstation iii",
      "playstation iii",
    ],
    icon: "/consoles/ps3_02_30g.png",
  },
  {
    gamesdb_id: 4919,
    screenscrapper_id: 60,
    name: "sony playstation 4",
    extensions: ["zip", "7z", "iso"],
    foldernames: [
      "playstation 4",
      "sony playstation 4",
      "sony ps4",
      "ps4",
      "sony playstation iv",
      "playstation iv",
    ],
    icon: "/consoles/ps4.png",
  },
  {
    screenscrapper_id: 61,
    gamesdb_id: 13,
    name: "sony playstation portable",
    extensions: ["zip", "7z", "img", "pbp", "bin", "iso", "cue", "cso"],
    foldernames: [
      "psp",
      "playstation portable (psp)",
      "sony psp",
      "sony playstation portable",
      "playstation portable",
      "sony ps portable",
      "ps portable",
    ],
    icon: "/consoles/psp_01.png",
  },
  {
    gamesdb_id: 39,
    screenscrapper_id: 62,
    name: "sony playstation vita",
    extensions: ["zip", "7z", "iso", "vpk"],
    foldernames: [
      "ps vita",
      "sony playstation vita",
      "playstation vita",
      "sony ps vita",
      "sony vita",
      "vita",
    ],
    icon: "/consoles/psvita.png",
  },
  {
    gamesdb_id: 4916,
    screenscrapper_id: 63,
    name: "google android",
    extensions: ["zip", "7z", "apk"],
    foldernames: ["android"],
    icon: "/consoles/android.png",
  },
  {
    screenscrapper_id: 64,
    name: "commodore amiga 600",
    extensions: [
      "zip",
      "7z",
      "adf",
      "adz",
      "ipf",
      "uae",
      "hdf",
      "hdz",
      "dms",
      "exe",
      "cpio",
      "rom",
      "lha",
      "m3u",
    ],
    foldernames: [
      "amiga",
      "amiga600",
      "commodore amiga",
      "commodore amiga 500",
      "commodore amiga 1200",
      "commodore amiga 600",
      "commodore amiga 2000",
      "commodore amiga 3000",
      "commodore amiga 4000",
      "commodore amiga 500+",
      "commodore amiga 1000",
      "commodore a500",
      "commodore a1200",
      "commodore a600",
      "commodore a2000",
      "commodore a3000",
      "commodore a4000",
      "commodore a500+",
      "commodore a1000",
      "amiga 500",
      "amiga 1200",
      "amiga 600",
      "amiga 2000",
      "amiga 3000",
      "amiga 4000",
      "amiga 500+",
      "amiga 1000",
      "a500",
      "a1200",
      "a600",
      "a2000",
      "a3000",
      "a4000",
      "a500+",
      "a1000",
    ],
    icon: "/consoles/amiga.png",
  },
  {
    gamesdb_id: 4914,
    screenscrapper_id: 65,
    name: "amstrad cpc",
    extensions: ["zip", "7z", "bin", "cpr", "dsk", "cpc"],
    foldernames: [
      "cpc",
      "amstradcpc",
      "amstrad cpc",
      "amstrad cpc 464",
      "amstrad cpc 472",
      "amstrad cpc 664",
      "amstrad cpc 6128",
      "amstrad cpc 464 plus",
      "amstrad cpc 6128 plus",
      "amstrad cpc 464+",
      "amstrad cpc 6128+",
      "amstrad 464 plus",
      "amstrad 6128 plus",
      "amstrad 464+",
      "amstrad 6128+",
      "cpc 464",
      "cpc 472",
      "cpc 664",
      "cpc 6128",
      "cpc 464 plus",
      "cpc 6128 plus",
      "cpc 464+",
      "cpc 6128+",
      "464 plus",
      "6128 plus",
      "464+",
      "6128+",
    ],
    icon: "/consoles/cpc.png",
  },
  {
    gamesdb_id: 40,
    screenscrapper_id: 66,
    name: "commodore 64",
    extensions: [
      "zip",
      "7z",
      "arc",
      "ark",
      "bin",
      "c64",
      "crt",
      "d64",
      "d71",
      "d81",
      "dmp",
      "g64",
      "lnx",
      "nbz",
      "nib",
      "p00",
      "prg",
      "reu",
      "sda",
      "sfx",
      "t64",
      "tap",
      "z64",
    ],
    foldernames: ["commodore 64", "c64", "commodore 128", "commodore"],
    icon: "/consoles/c64.png",
  },
  {
    name: "super cassette vision",
    gamesdb_id: 4966,
    screenscrapper_id: 67,
    extensions: ["zip", "7z", "bin", "cart"],
    foldernames: [
      "super cassette vision",
      "epoch super cassette vision",
      "yeno super cassette vision",
    ],
    icon: "/consoles/supercasettevision1.png",
  },
  {
    name: "snk neo geo mvs",
    screenscrapper_id: 68,
    extensions: ["zip", "7z", "chd"],
    foldernames: ["neo-geo mvs", "snk neo geo mvs", "snk neo-geo mvs"],
    icon: "/consoles/neogeo.png",
  },
  {
    gamesdb_id: 4956,
    screenscrapper_id: 70,
    name: "snk neo geo cd",
    extensions: ["zip", "7z", "bin", "ccd", "cue", "img", "iso"],
    foldernames: [
      "neo-geo cd",
      "neogeocd",
      "snk neo geo cd",
      "snk neo-geo cd-rom",
      "neo-geo cd-rom",
      "snk neo-geo cd",
      "neogeocdjp",
      "neocd",
    ],
    icon: "/consoles/neogeocdz.png",
  },
  {
    gamesdb_id: 4930,
    screenscrapper_id: 72,
    name: "nec pc-fx",
    extensions: ["zip", "7z", "bin", "chd", "ccd", "img", "sub", "cue"],
    foldernames: ["pc-fx", "pcfx", "nec pc-fx"],
    icon: "/consoles/pcfx01.png",
  },
  {
    gamesdb_id: 4945,
    screenscrapper_id: 73,
    name: "commodore vic-20",
    extensions: ["zip", "7z", "crt", "d64", "prg", "t64", "tap", "d81"],
    foldernames: ["vic-20", "c64", "commodore vic-20", "vic20", "commodore"],
    icon: "/consoles/vic20.png",
  },
  {
    gamesdb_id: 4964,
    name: "casio pv-100",
    screenscrapper_id: 74,
    extensions: ["zip", "7z", "bin"],
    foldernames: ["pv-1000", "casio pv-1000"],
    icon: "consoles/pv1000.png",
  },
  {
    screenscrapper_id: 76,
    extensions: [
      "zip",
      "7z",
      "csw",
      "dsk",
      "fdi",
      "img",
      "ipf",
      "mgt",
      "rom",
      "rzx",
      "scl",
      "slt",
      "sp",
      "tap",
      "trd",
      "tzx",
      "sna",
      "szx",
      "udi",
      "z80",
    ],
    gamesdb_id: 4913,
    name: "sinclair zx spectrum",
    foldernames: [
      "zx spectrum",
      "zxspectrum",
      "sinclair zx spectrum",
      "sinclair zx-spectrum",
      "zx-spectrum",
      "zxs",
    ],
    icon: "/consoles/zxs.png",
  },
  {
    gamesdb_id: 5010,
    screenscrapper_id: 77,
    name: "sinclair zx81",
    extensions: ["zip", "7z", "c", "p", "tzx"],
    foldernames: [
      "zx81",
      "sinclair zx-81",
      "sinclair zx81",
      "zx-81",
      "zxeightyone",
    ],
    icon: "consoles/zx81.png",
  },
  {
    gamesdb_id: 4974,
    name: "entex adventure vision",
    screenscrapper_id: 78,
    extensions: ["zip", "7z", "bin"],
    foldernames: ["adventure vision", "entex adventure vision"],
    icon: "/consoles/adventure_vision.png",
  },
  {
    gamesdb_id: 4931,
    screenscrapper_id: 79,
    name: "sharp x68000",
    extensions: [
      "zip",
      "7z",
      "dim",
      "img",
      "d88",
      "88d",
      "hdm",
      "dup",
      "2hd",
      "xdf",
      "hdf",
      "cmd",
      "m3u",
    ],
    foldernames: ["sharp x68000", "x68000", "sharp x68k", "x68k"],
    icon: "/consoles/x6800.png",
  },
  {
    gamesdb_id: 4928,
    screenscrapper_id: 80,
    name: "fairchild channel f",
    extensions: ["zip", "7z", "bin"],
    foldernames: [
      "channel f",
      "channelf",
      "fairchild channel f",
      "fairchild video entertainment system",
      "fairchild ves",
      "fairchild",
      "video entertainment system",
      "ves",
    ],
    icon: "/consoles/fairchild.png",
  },
  {
    name: "action max",
    screenscrapper_id: 81,
    gamesdb_id: 4976,
    extensions: ["zip", "7z", "singe"],
    foldernames: ["action max", "wow action max", "world of wonder action max"],
    icon: "/consoles/action_max.png",
  },
  {
    gamesdb_id: 4923,
    screenscrapper_id: 82,
    name: "snk neo geo pocket color",
    extensions: ["zip", "7z", "ngp", "ngc", "bin"],
    foldernames: [
      "neo-geo pocket color",
      "ngpc",
      "ngp",
      "neo geo pocket color (ngpc)",
      "snk neo geo pocket color",
      "snk neo-geo pocket color",
      "snk neo-geo pc",
      "neo-geo pc",
      "snk ngpc",
    ],
    icon: "/consoles/neogeopocket_b.png",
  },
  {
    name: "aamber pegasus",
    screenscrapper_id: 83,
    extensions: ["zip", "7z", "bin"],
    foldernames: ["aamber pegasus"],
    icon: "/consoles/pegasus.png",
  },
  {
    gamesdb_id: 4944,
    name: "acorn archimedes",
    screenscrapper_id: 84,
    extensions: ["zip", "7z", "cue", "iso", "adf", "jfd"],
    foldernames: ["archimedes", "acorn archimedes"],
    icon: "/consoles/archimedes.png",
  },
  {
    gamesdb_id: 4954,
    name: "acorn electron",
    screenscrapper_id: 85,
    extensions: ["zip", "7z", "bin", "sdd", "uef"],
    foldernames: ["electron", "acorn electron"],
    icon: "/consoles/electron.png",
  },
  {
    screenscrapper_id: 86,
    gamesdb_id: 4942,
    name: "apple ii",
    extensions: ["zip", "7z", "dsk", "do", "po", "nib"],
    foldernames: [
      "apple ii",
      "apple2",
      "apple iigs",
      "apple ii+",
      "apple iic",
      "apple iic+",
      "apple iic plus",
      "apple iie",
      "apple 2",
      "apple 2+",
      "apple 2c",
      "apple 2c+",
      "apple 2c plus",
      "apple 2e",
      "apple 2gs",
      "apple iii",
      "apple 3",
      "apple i",
      "apple 1",
    ],
    icon: "/consoles/apple2.png",
  },
  {
    screenscrapper_id: 87,
    gamesdb_id: 4999,
    name: "amstrad gx4000",
    extensions: ["zip", "7z", "bin", "cpr", "dsk", "cpc"],
    foldernames: ["gx4000", "amstrad gx4000", "amstrad gx-4000", "gx-4000"],
    icon: "/consoles/gx400.png",
  },
  {
    name: "camputers lynx",
    screenscrapper_id: 88,
    extensions: ["zip", "7z", "ldf", "tap"],
    foldernames: [
      "camputers lynx",
      "camputers lynx 48",
      "camputers lynx 96",
      "camputers lynx 128",
      "lynx 48",
      "lynx 96",
      "lynx 128",
    ],
    icon: "/consoles/lynx.png",
  },
  {
    name: "coleco adam",
    screenscrapper_id: 89,
    extensions: ["zip", "7z", "bas", "com", "ddp", "dsk", "img", "lbr"],
    foldernames: ["adam", "coleco adam"],
    icon: "/consoles/col.png",
  },
  {
    name: "mega duck",
    screenscrapper_id: 90,
    extensions: ["zip", "7z", "bin"],
    foldernames: [
      "mega duck",
      "cougar boy",
      "creatronic mega duck",
      "megaduck",
    ],
    icon: "/consoles/megaduck.png",
  },
  {
    screenscrapper_id: 91,
    name: "dragon data dragon 32",
    extensions: [
      "zip",
      "7z",
      "asc",
      "bas",
      "cas",
      "ccc",
      "dmk",
      "dsk",
      "jvc",
      "os9",
      "rom",
      "sna",
      "vdk",
      "wav",
    ],
    gamesdb_id: 4952,
    foldernames: [
      "dragon 32/64",
      "dragon",
      "dragon32",
      "dragon 32-64",
      "dragon data dragon",
      "dragon 32",
      "dragon 64",
    ],
    icon: "/consoles/datadragon.png",
  },
  {
    name: "colour genie",
    screenscrapper_id: 92,
    extensions: ["zip", "7z", "cas"],
    foldernames: [
      "eg2000 colour genie",
      "eaca eg2000 colour genie",
      "eaca eg-2000 colour genie",
      "eaca colour genie",
      "eaca eg-2000",
      "colour genie",
      "eg-2000",
    ],
    icon: "/consoles/colorgenie.png",
  },
  {
    screenscrapper_id: 93,
    name: "electronika bk",
    extensions: [
      "zip",
      "7z",
      "bas",
      "bin",
      "cod",
      "doc",
      "exe",
      "mus",
      "pig",
      "bkd",
      "img",
    ],
    foldernames: [
      "bk",
      "elektronika bk",
      "electonika bk",
      "electonika bk-0010",
      "electonika bk-0010.01",
      "electonika bk-0010sh",
      "electonika bk-0011",
      "electonika bk-0011m",
      "bk-0010",
      "bk-0010.01",
      "bk-0010sh",
      "bk-0011",
      "bk-0011m",
    ],
    icon: "/consoles/bk.png",
  },
  {
    gamesdb_id: 4963,
    screenscrapper_id: 94,
    name: "emerson arcadia 2001",
    extensions: ["zip", "7z", ".bin", ".7z", ".zip"],
    foldernames: [
      "arcadia 2001",
      "emerson arcadia 2001",
      "emerson radio arcadia 2001",
      "emerson 2001",
      "advision home arcade",
      "bandai arcadia",
      "tele-fever",
      "leonardo",
      "hmg-2650",
      "home arcade centre",
      "intercord xl 2000 system",
      "leisure-vision",
      "tunix home arcade",
      "schmid tvg-2000",
      "tele-computer cosmos",
      "intelligent game mpt-03",
      "hanimex mpt-03",
      "itmc mpt-03",
      "dynavision",
      "p.i.c ekusera",
      "poppy mpt-03 tele computer spiel",
      "prestige video computer game mpt-03",
      "rowtron 2000",
      "rowtron video computer game mpt-03",
      "soundic mpt-03",
      "tempest video computer game",
      "tobby mpt-03",
      "tryom video game center",
      "grandstand video master",
      "uvi compu-game",
      "intervision 2001",
      "ormatu 2001",
      "sheen home video centre 2001",
      "tele brain",
      "palladium video computer game",
      "polybrain video computer game",
      "trakton computer video game",
    ],
    icon: "/consoles/arcadia2001.png",
  },
  {
    name: "epoch game pocket computer",
    screenscrapper_id: 95,
    extensions: ["zip", "7z", "bin"],
    foldernames: ["game pocket computer", "epoch game pocket computer"],
    icon: "/consoles/epoch-game-pocket.png",
  },
  {
    name: "exelvision exl 100",
    screenscrapper_id: 96,
    extensions: ["zip", "7z", "bas", "bin", "fd", "k7", "rom", "td0", "wav"],
    foldernames: ["exl 100", "exelvision exl 100"],
    icon: "/consoles/exl_100.png",
  },
  {
    gamesdb_id: 4978,
    name: "fujitsu fm-7",
    screenscrapper_id: 97,
    extensions: ["zip", "7z", "d77", "t77"],
    foldernames: [
      "fm-7",
      "fujitsu fm-7",
      "fujitsu micro 7",
      "fm-new 7",
      "fm-77",
      "fm-77av",
      "fm-8",
    ],
    icon: "/consoles/fm7.png",
  },
  {
    gamesdb_id: 4991,
    name: "casio loopy",
    screenscrapper_id: 98,
    extensions: ["zip", "7z", "bin"],
    foldernames: ["loopy", "casio loopy"],
    icon: "/consoles/loopy.png",
  },
  {
    gamesdb_id: 5006,
    name: "commodore 16",
    screenscrapper_id: 99,
    parentid: 66,
    extensions: ["zip", "7z", "crt", "d64", "g64", "lnx", "prg", "tap", "z64"],
    foldernames: [
      "plus/4",
      "commodore plus 4",
      "commodore 16 & plus4",
      "commodore plus/4",
      "commodore 16",
      "commodore minus/60",
      "minus/60",
    ],
    icon: "/consoles/c16.png",
  },
  {
    name: "super a'can",
    screenscrapper_id: 100,
    extensions: ["zip", "7z", "bin"],
    foldernames: ["super a'can", "funtech super acan", "funtech super a'can"],
    icon: "/consoles/super_acan.png",
  },
  {
    gamesdb_id: 5015,
    name: "gp32",
    screenscrapper_id: 101,
    extensions: ["zip", "7z", "fpk", "smc"],
    foldernames: ["gp32", "gamepark 32", "game park 32"],
    icon: "/consoles/gp32.png",
  },
  {
    gamesdb_id: 4939,
    screenscrapper_id: 102,
    extensions: ["zip", "7z", "vec", "bin", "gam"],
    name: "smith engineering vectrex",
    foldernames: ["gce vectrex", "vectrex"],
    icon: "/consoles/vectrex.png",
  },
  {
    screenscrapper_id: 103,
    name: "hartung game master",
    extensions: ["zip", "7z", "bin"],
    foldernames: [
      "game master",
      "hartung game master",
      "systema 2000",
      "super game",
      "game tronic",
      "gmaster",
    ],
    icon: "/consoles/game_master.png",
  },
  {
    gamesdb_id: 4927,
    screenscrapper_id: 104,
    name: "magnavox odyssey",
    extensions: ["zip", "7z", "bin"],
    foldernames: [
      "videopac g7000",
      "magnavox odyssey²",
      "o2em",
      "odyssey2",
      "odyssey",
      "videopac",
      "videopac",
      "magnavox odyssey 2",
      "philips videopac plus g7400",
      "magnavox odyssey2",
      "philips videopac",
      "radiola videopac",
      "schneider videopac",
      "siera videopac",
      "brandt jopac",
      "continental edision jopac",
      "sabe jopac",
      "philips videopac g7000",
      "philips videopac c52",
      "radiola videopac jet 25",
      "philips videopac g7200",
      "radiola videopac jet 27",
      "schneider videopac 7200",
      "philips videopac n60",
      "philips videopac+ g7400",
      "radiola videopac jet 47",
      "radiola videopac jet 74+",
      "brandt japac jo7400",
      "continental edison jopac jo 1450",
      "philips videopac c7420",
      "philips videopac g7401",
      "radiola videopac jet 471",
      "radiola videopac jet 741+",
      "odyssey²",
      "jopac",
      "videopac c52",
      "videopac n60",
      "videopac jet 25",
      "videopac g7200",
      "videopac jet 27",
      "videopac 7200",
      "videopac+ g7400",
      "videopac jet 47",
      "videopac jet 74+",
      "japac jo 7400",
      "jopac jo 1450",
      "videopac c7420",
      "videopac g7401",
      "videopac jet 471",
      "videopac jet 741+",
      "g7000",
      "g7200",
      "g7400",
      "jo 7400",
      "jo 1450",
      "c7420",
      "g7401",
    ],
    icon: "/consoles/odyssey01.png",
  },
  {
    screenscrapper_id: 105,
    name: "nec supergrafx",
    parentid: 31,
    extensions: ["zip", "7z", "pce", "cue", "ccd", "sgx"],
    foldernames: [
      "pc engine supergrafx",
      "supergrafx",
      "nec supergrafx",
      "nec pc engine supergrafx",
      "sgfx",
    ],
    icon: "/consoles/pce_supergrafx01.png",
  },
  {
    screenscrapper_id: 106,
    gamesdb_id: 4936,
    parentid: 3,
    name: "nintendo famicom disk system",
    extensions: ["zip", "7z", "fds", "nes", "bin"],
    foldernames: [
      "family computer disk system",
      "famiri konpyuta disuku shisutemu",
      "fds",
      "nintendo famicom disk system",
      "nintendo family computer disk system",
      "nintendo famiri konpyuta disuku shisutemu",
      "nintendo famikom disk system",
      "nintendo fds",
      "nintendo fcds",
      "nintendo fcd",
      "nintendo fkds",
      "famicom disk system",
      "famikom disk system",
      "fcds",
      "fcd",
      "fkds",
    ],
    icon: "/consoles/fc_disksystem02.png",
  },
  {
    screenscrapper_id: 107,
    name: "nintendo satellaview",
    parentid: 4,
    extensions: ["zip", "7z", "sfc"],
    foldernames: [
      "satellaview",
      "nintendo satellaview",
      "nintendo bs-x",
      "bs-x",
    ],
    icon: "/consoles/satella.png",
  },
  {
    screenscrapper_id: 108,
    name: "bandai sufami turbo",
    parentid: 4,
    extensions: ["zip", "7z", "sfc", "st", "smc"],
    foldernames: ["sufami turbo", "sufami", "bandai sufami turbo"],
    icon: "/consoles/sufami.png",
  },
  {
    gamesdb_id: 4949,
    screenscrapper_id: 109,
    name: "sega sg-1000",
    parentid: 2,
    extensions: ["zip", "7z", "sg", "bin"],
    foldernames: [
      "sg-1000",
      "sg1000",
      "sega sg-1000",
      "sega game 1000",
      "sg-1000 ii",
      "sg-1000 2",
      "sc 3000",
      "othello multivisio",
      "segasgone",
    ],
    icon: "/consoles/sg-1000b.png",
  },
  {
    gamesdb_id: 4911,
    screenscrapper_id: 111,
    parentid: 64,
    name: "commodore amiga",
    extensions: [
      "zip",
      "7z",
      "adf",
      "adz",
      "ipf",
      "uae",
      "hdf",
      "hdz",
      "dms",
      "exe",
      "cpio",
      "rom",
      "lha",
      "m3u",
    ],
    foldernames: [
      "amiga (aga)",
      "amiga1200",
      "amiga",
      "commodore amiga",
      "amiga aga",
    ],
    icon: "/consoles/amiga.png",
  },
  {
    gamesdb_id: 4929,
    screenscrapper_id: 113,
    name: "msx",
    extensions: ["zip", "7z", "mx1", "rom", "dsk", "col", "cas"],
    foldernames: ["msx", "msx1", "microsoft msx", "microsoft msx1"],
    icon: "/consoles/msx.png",
  },
  {
    gamesdb_id: 4955,
    screenscrapper_id: 114,
    name: "nec turbografx cd",
    parentid: 31,
    extensions: ["zip", "7z", "pce", "cue", "ccd", "chd", "iso", "sgx"],
    foldernames: [
      "pc engine cd-rom",
      "pcenginecd",
      "pce-cd",
      "tg-cd",
      "nec pc engine-cd",
      "nec turbografx-cd",
      "nec pc engine cd-rom",
      "nec pc engine cd",
      "pc engine cd",
      "pcecd",
    ],
    icon: "/consoles/pce_cdrom.png",
  },
  {
    screenscrapper_id: 115,
    gamesdb_id: 32,
    name: "mattel electronics intellivision",
    extensions: ["zip", "7z", "bin", "int", "rom"],
    foldernames: [
      "intellivision",
      "mattel intellivision",
      "mattel intelliputer",
      "intelliputer",
      "mattel intellivision ii",
      " intellivision ii",
      "mattel intellivision 2",
      " intellivision 2",
      "mattel ecs",
      "intv iii",
      "intv super pro system",
      "super pro system",
    ],
    icon: "/consoles/intellivision.png",
  },
  {
    screenscrapper_id: 116,
    name: "msx2",
    parentid: 113,
    extensions: ["zip", "7z", "mx2", "rom", "cas", "dsk"],
    foldernames: ["msx2", "msx", "microsoft msx2"],
    icon: "/consoles/msx.png",
  },
  {
    name: "msx2+",
    screenscrapper_id: 117,
    parentid: 113,
    extensions: ["zip", "7z", "mx2", "rom", "cas", "dsk"],
    foldernames: [
      "msx2+",
      "msx",
      "msx2",
      "microsoft msx2+",
      "microsoft msx2plus",
      "msx2plus",
    ],
    icon: "/consoles/msx.png",
  },
  {
    screenscrapper_id: 118,
    name: "msx turbo r",
    parentid: 113,
    extensions: ["zip", "7z", "mx1", "mx2", "rom", "dsk", "col"],
    foldernames: [
      "msx turbo r",
      "msxturbor",
      "msx",
      "microsoft msx",
      "microsoft msx r turbo",
      "msx-r turbo",
    ],
    icon: "/consoles/msx.png",
  },
  {
    name: "nntendo gba e-reader",
    screenscrapper_id: 119,
    parentid: 12,
    foldernames: [
      "gba e-reader",
      "nintendo gameboy advance e-reader",
      "nintendo gb advance e-reader",
      "nintendo gba e-reader",
      "nintendo e-reader",
      "gameboy advance e-reader",
      "gb advance e-reader",
    ],
    icon: "/consoles/gba008.png",
    extensions: ["zip", "7z"],
  },
  {
    gamesdb_id: 4988,
    name: "v.smile",
    screenscrapper_id: 120,
    extensions: ["zip", "7z", "bin"],
    foldernames: ["v.smile", "vtech v.smile"],
    icon: "/consoles/vsmile.png",
  },
  {
    gamesdb_id: 4940,
    name: "game.com",
    screenscrapper_id: 121,
    extensions: ["zip", "7z", "bin"],
    foldernames: ["game.com", "tiger game.com", "game-com"],
    icon: "/consoles/game_com.png",
  },
  {
    screenscrapper_id: 122,
    parentid: 14,
    extensions: ["zip", "7z", "ndd"],
    name: "nintendo 64dd",
    foldernames: [
      "nintendo 64dd",
      "64dd",
      "n64",
      "nintendo 64 dd",
      "n64 dd",
      "64 dd",
    ],
    icon: "/consoles/n64dd01.png",
  },
  {
    screenscrapper_id: 123,
    name: "scummvm game engine",
    parentid: 135,
    extensions: ["zip", "7z", "svm", "scummvm", "residualvm"],
    foldernames: ["scummvm", "residualvm"],
    icon: "/consoles/scummvm.png",
  },
  {
    name: "radio-86rk",
    screenscrapper_id: 124,
    extensions: ["zip", "7z", "rkm"],
    foldernames: ["mikrosha", "radio-86rk mikrosha", "mikrosha computer"],
    icon: "/consoles/86rk.png",
  },
  {
    name: "pecom 64",
    screenscrapper_id: 125,
    extensions: ["zip", "7z", "wav"],
    foldernames: ["pecom 64"],
    icon: "/consoles/pecom64.png",
  },
  {
    screenscrapper_id: 126,
    name: "jupiter ace",
    extensions: ["zip", "7z", "a22", "ace", "asm", "dsk", "tap", "wav"],
    foldernames: ["jupiter ace", "ace4000", "jupiter ace 4000", "ace 4000"],
    icon: "/consoles/jupiter.png",
  },
  {
    name: "super gameboy",
    screenscrapper_id: 127,
    parentid: 9,
    foldernames: [
      "super game boy",
      "sgb",
      "nintendo super game boy",
      "nintendo super gameboy",
      "super gameboy",
      "nintendo super gg",
      "super gb",
    ],
    icon: "/consoles/sgb.png",
    extensions: ["zip", "7z"],
  },
  {
    screenscrapper_id: 129,
    name: "commodore cdtv",
    parentid: 64,
    extensions: ["zip", "7z", "bin", "ccd", "cue", "img", "iso", "wav"],
    foldernames: [
      "amiga cdtv",
      "amigacdtv",
      "amiga",
      "commodore cdtv",
      "commodore amiga cdtv",
      "amliga cdtv",
      "cdtv",
    ],
    icon: "/consoles/amiga.png",
  },
  {
    gamesdb_id: 4947,
    screenscrapper_id: 130,
    name: "commodore amiga cd32",
    extensions: [
      "zip",
      "7z",
      "bin",
      "ccd",
      "cdt",
      "cue",
      "img",
      "iso",
      "nrg",
      "sub",
    ],
    foldernames: [
      "amiga cd32",
      "amigacd32",
      "amiga",
      "commodore amiga cd32",
      " amiga cd32",
    ],
    icon: "/consoles/amigacd32.png",
  },
  {
    screenscrapper_id: 131,
    name: "tangerine computer systems oric",
    extensions: ["zip", "7z", "bas", "bin", "dsk", "tap"],
    foldernames: [
      "oric 1 / atmos",
      "oric",
      "oric atmos",
      "tangerine oric",
      "tangerince oric atmos",
      "tangerine oric-1",
      "tangerine oric-i",
      "oric-1",
      "oric-i",
      "eurêka oric atmos",
      "eurêka oric telestrat",
      "eurêka oric nova 64",
      "eurêka oric adresstal",
      "eurêka telestrat",
      "eurêka nova 64",
      "eurêka adresstal",
    ],
    icon: "/consoles/atmos.png",
  },
  {
    gamesdb_id: 4917,
    screenscrapper_id: 133,
    name: "philips cd-i",
    extensions: ["zip", "7z", "bin", "cue", "iso", "nrg", "wav"],
    foldernames: ["cd-i", "philips cd-i", "cdimono1"],
    icon: "/consoles/cdi.png",
  },
  {
    screenscrapper_id: 135,
    gamesdb_id: 1,
    name: "dos (pc)",
    extensions: [
      "zip",
      "7z",
      "pc(exe|com|iso|bin|mdf|ima|img|gog|dsk|z5|z8|bas|dat)",
      "dos(exe|com|iso|bin|mdf|ima|img|gog|dsk|z5|z8|bas|dat)",
      "wad",
      "game",
    ],
    foldernames: [
      "pc dos",
      "pc",
      "ms-dos",
      "microsoft ms-dos",
      "microsoft dos",
      "dos",
      "pc-dos",
      "dosbox",
      "exodos",
      "total dos collection",
      "total dos",
      "prboom",
    ],
    icon: "/consoles/dos.png",
  },
  {
    screenscrapper_id: 136,
    parentid: 135,
    extensions: [
      "zip",
      "7z",
      "pc(exe|dll|com|iso|bin|mdf|img)",
      "dos(exe|dll|com|iso|bin|mdf|img)",
    ],
    name: "microsoft windows 3.x",
    foldernames: [
      "pc win3.xx",
      "windows 3.x",
      "microsoft windows 3.x",
      "microsoft windows 3.1",
      "windows 3.1",
      "win 3.1",
      "w3.1",
      "microsoft windows 3.0",
      "windows 3.0",
      "win 3.0",
      "w3.0",
    ],
    icon: "/consoles/windows3.png",
  },
  {
    screenscrapper_id: 137,
    parentid: 135,
    name: "microsoft windows 95",
    foldernames: [
      "pc win9x",
      "microsoft windows 95",
      "microsoft windows 98",
      "microsoft windows 98se",
      "microsoft windows 98se2",
      "microsoft windows millenium",
      "windows 95",
      "windows 98",
      "windows 98se",
      "windows 98se2",
      "windows millenium",
      "win 95",
      "win 98",
      "win 98se",
      "win 98se2",
      "win millenium",
      "w95",
      "w98",
      "w98se",
      "w98se2",
    ],
    icon: "/consoles/windows95.png",
    extensions: ["zip", "7z"],
  },
  {
    screenscrapper_id: 138,
    name: "microsoft windows",
    foldernames: [
      "pc windows",
      "windows",
      "microsoft windows",
      "microsoft windows xp",
      "microsoft windows 2000",
      "microsoft windows vista",
      "microsoft windows 7",
      "microsoft windows 8",
      "microsoft windows 8.1",
      "microsoft windows 10",
      "windows xp",
      "windows 2000",
      "windows vista",
      "windows 7",
      "windows 8",
      "windows 8.1",
      "windows 10",
      "win xp",
      "win 2000",
      "win vista",
      "win 7",
      "win 8",
      "win 8.1",
      "win 10",
      "wxp",
      "w2000",
      "w7",
      "w8",
      "w8.1",
      "w10",
    ],
    icon: "/consoles/windows95.png",
    extensions: ["zip", "7z"],
  },
  {
    screenscrapper_id: 141,
    name: "thomson to8",
    extensions: ["zip", "7z", "fd", "k7", "m7", "qd", "sap", "m5", "wav"],
    foldernames: [
      "thomson mo/to",
      "to8",
      "thomson to7",
      "thomson mo5",
      "thomson to7-70",
      "thomson to8",
      "thomson to8d",
      "thomson to9",
      "thomson to9+",
      "to7",
      "to7-70",
      "to8d",
      "to9",
      "to9+",
      "thomson to9 plus",
      "to9 plus",
      "thomson to",
      "thomson mo5e",
      "thomson mo5nr",
      "thomson mo6",
      "olivetti prodest pc128",
      "mo5",
      "mo5e",
      "mo5nr",
      "mo6",
      "thomson mo",
    ],
    icon: "/consoles/thomsonto8.png",
  },
  {
    screenscrapper_id: 142,
    gamesdb_id: 24,
    name: "snk neo geo",
    extensions: ["zip", "7z", "chd"],
    foldernames: [
      "neo-geo",
      "neogeo",
      "snk neo geo",
      "snk neo-geo",
      "snk neo-geo aes",
      "neo-geo aes",
      "snk neo-geo mvs",
      "neo-geo mvs",
    ],
    icon: "/consoles/neogeo.png",
  },
  {
    screenscrapper_id: 143,
    name: "pinball fx2",
    extensions: ["zip", "7z", " "],
    foldernames: ["pinball fx2"],
    icon: "/consoles/pinball.png",
  },
  {
    screenscrapper_id: 144,
    name: "tandy trs-80",
    extensions: [
      "zip",
      "7z",
      "cas",
      "wav",
      "bas",
      "asc",
      "dmk",
      "jvc",
      "os9",
      "dsk",
      "vdk",
      "rom",
      "ccc",
      "sna",
    ],
    foldernames: [
      "trs-80 color computer",
      "coco",
      "tandy trs-80 color computer",
      "tandy trs-80",
      "tandy trs-80 coco",
      "trs-80 coco",
    ],
    icon: "/consoles/trs-80.png",
  },
  {
    screenscrapper_id: 145,
    foldernames: ["linux"],
    icon: "/consoles/linux.png",
    name: "linux",
    extensions: ["zip", "7z"],
  },
  {
    screenscrapper_id: 146,
    name: "apple macintosh",
    gamesdb_id: 37,
    extensions: ["zip", "7z", "img", "rom"],
    foldernames: [
      "mac os",
      "macintosh",
      "apple mac os",
      "apple mac-os",
      "apple mac-osx",
      "apple os",
      "apple osx",
      "mac-osx",
      "mac-os",
      "osx",
    ],
    icon: "/consoles/apple.png",
  },
  {
    gamesdb_id: 29,
    screenscrapper_id: 171,
    name: "atari jaguar cd",
    extensions: ["zip", "7z", "bin", "ccd", "cdi", "cue", "img", "nrg", "sub"],
    foldernames: [
      "jaguar cd",
      "atari jaguar cd",
      "atari jaguar cd-rom",
      "jaguar cd-rom",
    ],
    icon: "/consoles/jaguarcd.png",
  },
  {
    name: "sony playstation minis",
    screenscrapper_id: 172,
    parentid: 61,
    extensions: ["zip", "7z", "iso", "pbp", "cso"],
    foldernames: [
      "playstation minis",
      "psp",
      "sony psp minis",
      "sony playstation minis",
      "sony ps minis",
      "ps minis",
    ],
    icon: "/consoles/ps_pokesta01.png",
  },
  {
    name: "arcade",
    gamesdb_id: 23,
    screenscrapper_id: 75,
    extensions: ["zip", "7z", "chd"],
    foldernames: [
      "arcade",
      "mame",
      "fba",
      "fba_libretro",
      "mame-advmame",
      "mame-libretro",
      "mame-mame4all",
      "mess",
      "mame2003plus",
      "fbneo",
      "fba2012",
      "mame2000",
    ],
    icon: "/consoles/arcade.png",
  },

  {
    name: "visual pinball",
    screenscrapper_id: 198,
    extensions: ["zip", "7z", "vpt", "vpx"],
    foldernames: ["visual pinball"],
    icon: "/consoles/pinball.png",
  },
  {
    name: "future pinball",
    screenscrapper_id: 199,
    extensions: ["zip", "7z", "ftp"],
    foldernames: ["future pinball"],
    icon: "/consoles/pinball.png",
  },
  {
    name: "the pinball arcade",
    screenscrapper_id: 200,
    parentid: 197,
    extensions: ["zip", "7z", "chd"],
    foldernames: ["the pinball arcade"],
    icon: "/consoles/pinball.png",
  },
  {
    screenscrapper_id: 201,
    parentid: 143,
    name: "pinball fx3",
    extensions: ["zip", "7z"],
    foldernames: ["pinball fx3"],
    icon: "/consoles/pinball.png",
  },
  {
    gamesdb_id: 4953,
    screenscrapper_id: 205,
    name: "texas instruments ti-99",
    extensions: ["zip", "7z", "bin", "c", "dsk", "g", "ctg"],
    foldernames: ["ti-99/4a", "ti99", "texas instruments ti 99/4a", "ti-99"],
    icon: "/consoles/ti99.png",
  },
  {
    screenscrapper_id: 206,
    name: "lutro game engine",
    extensions: ["zip", "7z", "lutro", "lua"],
    foldernames: ["lutro"],
    icon: "/consoles/lutro.png",
  },
  {
    gamesdb_id: 4959,
    screenscrapper_id: 207,
    name: "watara supervision",
    extensions: ["zip", "7z", "sv", "bin"],
    foldernames: ["watara supervision", "supervision"],
    icon: "/consoles/supervision.png",
  },
  {
    screenscrapper_id: 208,
    extensions: [
      "zip",
      "7z",
      "d98",
      "98d",
      "fdi",
      "fdd",
      "2hd",
      "tfd",
      "d88",
      "88d",
      "hdm",
      "xdf",
      "dup",
      "cmd",
      "hdi",
      "thd",
      "nhd",
      "hdd",
      "hdn",
    ],
    gamesdb_id: 4934,
    name: "nec pc-9800 series",
    foldernames: ["nec pc-9801", "pc98", "pc9801", "pcninetyeight"],
    icon: "/consoles/pcfx02.png",
  },
  {
    gamesdb_id: 4957,
    screenscrapper_id: 211,
    name: "nintendo pokémon mini",
    extensions: ["zip", "7z", "min"],
    foldernames: [
      "pokémon mini",
      "pokemini",
      "pokemon mini",
      " pokemini",
      "pokémon mini (pkm)",
      "poke",
    ],
    icon: "/consoles/pokemonmini_pink.png",
  },
  {
    gamesdb_id: 4979,
    screenscrapper_id: 213,
    name: "mgt sam coupé",
    extensions: ["zip", "7z", "dsk", "sad"],
    foldernames: ["mgt sam coupé", "samcoupe", "sam coupé"],
    icon: "/consoles/mgmt.png",
  },
  {
    screenscrapper_id: 214,
    name: "openbor game engine",
    extensions: ["zip", "7z", "pak"],
    foldernames: ["openbor"],
    icon: "/consoles/openbor.png",
  },
  {
    screenscrapper_id: 215,
    name: "z-machine",
    extensions: ["zip", "7z", "z3", "z6"],
    foldernames: ["z-machine"],
    icon: "/consoles/z-machine.png",
  },
  {
    screenscrapper_id: 216,
    extensions: ["zip", "7z", "uze"],
    name: "uzebox open source console",
    foldernames: ["uzebox"],
    icon: "/consoles/uzebox.png",
  },
  {
    screenscrapper_id: 217,
    name: "apple iigs",
    parentid: 86,
    extensions: ["zip", "7z", "2mg", "po", "nib", "do", "dsk", "hdv", "gsplus"],
    foldernames: ["apple iigs", "apple2gs", "appleiigs"],
    icon: "/consoles/appleiigs.png",
  },
  {
    screenscrapper_id: 218,
    name: "spectravideo",
    extensions: ["zip", "7z", " cas", "bin", "dsk"],
    foldernames: ["spectravideo"],
    icon: "/consoles/spectravideo.png",
  },
  {
    screenscrapper_id: 219,
    name: "palm os",
    extensions: ["zip", "7z", "prc", "pdb", "pqa", "img"],
    foldernames: ["palm os", "palm", "palmos"],
    icon: "/consoles/palmos.png",
  },
  {
    gamesdb_id: 4977,
    screenscrapper_id: 220,
    name: "sharp x1",
    extensions: [
      "zip",
      "7z",
      "dx1",
      "2d",
      "2hd",
      "tfd",
      "d88",
      "88d",
      "hdm",
      "xdf",
      "dup",
      "cmd",
    ],
    foldernames: ["sharp x1", "x1", "xone"],
    icon: "/consoles/sharpx1.png",
  },
  {
    gamesdb_id: 4933,
    screenscrapper_id: 221,
    name: "nec pc-8800 series",
    extensions: ["zip", "7z", "d88", "88d", "m3u"],
    foldernames: ["nec pc-8801", "pc88", "pceightyeight"],
    icon: "/consoles/pcfx02.png",
  },
  {
    screenscrapper_id: 222,
    name: "tic-80 game engine",
    extensions: ["zip", "7z", "tic"],
    foldernames: ["tic-80", "tic80", "tic"],
    icon: "/consoles/tic80.png",
  },
  {
    screenscrapper_id: 223,
    name: "solarus game engine",
    extensions: ["zip", "7z", "solarus"],
    foldernames: ["solarus"],
    icon: "/consoles/solarus.png",
  },
  {
    gamesdb_id: 4971,
    screenscrapper_id: 225,
    name: "nintendo switch",
    extensions: ["zip", "7z", ".zip"],
    foldernames: ["switch", "nintendo switch"],
    icon: "/consoles/switch.png",
  },
  {
    screenscrapper_id: 231,
    name: "easyrpg game engine",
    extensions: ["zip", "7z", "ini"],
    foldernames: ["easyrpg"],
    icon: "/consoles/easyrpg.png",
  },
  {
    screenscrapper_id: 234,
    name: "pico-8 fantasy console",
    extensions: ["zip", "7z", "p8", "png"],
    foldernames: ["pico-8", "pico8", "pico", "pico-8 (p8)", "fake08"],
    icon: "/consoles/pico.png",
  },
  {
    gamesdb_id: 5008,
    name: "commodore pet",
    screenscrapper_id: 240,
    extensions: [
      "zip",
      "7z",
      "a0",
      "b0",
      "crt",
      "d64",
      "d81",
      "prg",
      "tap",
      "t64",
    ],
    foldernames: ["pet"],
    icon: "/consoles/pet.png",
  },
  {
    gamesdb_id: 5005,
    screenscrapper_id: 241,
    name: "vtech creativision",
    extensions: ["zip", "7z", "bin", "rom"],
    foldernames: ["creativision", "crvision"],
    icon: "/consoles/creativision.png",
  },
  {
    screenscrapper_id: 244,
    name: "lowres nx fantasy console",
    extensions: ["zip", "7z", "nx"],
    foldernames: ["lowres nx", "lowresnx"],
    icon: "/consoles/lowresnx.png",
  },
  {
    screenscrapper_id: 250,
    gamesdb_id: 4958,
    name: "sega pico",
    extensions: ["zip", "7z", "md"],
    foldernames: ["sega pico", "kids computer pico"],
    icon: "/consoles/picno.png",
  },
  {
    screenscrapper_id: 253,
    name: "fm towns",
    extensions: ["zip", "7z", "cue", "bin"],
    foldernames: ["fm towns", "fmtmarty"],
    icon: "/consoles/fmmarty.png",
  },
  {
    name: "philips vg 5000",
    screenscrapper_id: 261,
    extensions: ["zip", "7z", "k7"],
    foldernames: ["philips vg 5000"],
    icon: "/consoles/vg-500.png",
  },
  {
    name: "wasm-4",
    screenscrapper_id: 262,
    extensions: ["zip", "7z", "wasm"],
    foldernames: ["wasm-4", "wasm"],
    icon: "/consoles/wasm.png",
  },
  {
    screenscrapper_id: 263,
    name: "arduboy miniature game system",
    extensions: ["zip", "7z", "hex"],
    foldernames: ["arduboy"],
    icon: "/consoles/arduoboy.png",
  },
  {
    name: "vircon32",
    screenscrapper_id: 272,
    foldernames: ["vircon32"],
    icon: "/consoles/v32.png",
    extensions: ["zip", "7z"],
  },
  {
    name: "voxatron",
    screenscrapper_id: 275,
    extensions: ["zip", "7z", "vx", "png"],
    foldernames: ["voxatron"],
    icon: "/consoles/voxatron.png",
  },
  {
    name: "video computer 4000",
    screenscrapper_id: 281,
    foldernames: ["vc 4000", "video computer 4000"],
    icon: "/consoles/vc-4000.png",
    extensions: ["zip", "7z"],
  },
  {
    gamesdb_id: 4980,
    name: "sony plastation 5",
    screenscrapper_id: 284,
    extensions: ["zip", "7z", "iso"],
    foldernames: [
      "playstation 5",
      "sony playstation 5",
      "sony ps5",
      "ps5",
      "sony playstation v",
      "playstation v",
    ],
    icon: "/consoles/ps5.png",
  },
  {
    name: "philips p2000t",
    screenscrapper_id: 287,
    extensions: ["zip", "7z", "cas"],
    foldernames: ["p2000t"],
    icon: "/consoles/p200t.png",
  },
  {
    name: "prboom",
    screenscrapper_id: 290,
    parentid: 135,
    extensions: ["zip", "7z", "wad"],
    foldernames: ["prboom", "port"],
    icon: "/consoles/prboom.png",
  },
]
