export const CONSOLES = [
  {
    name: "3DO Interactive Multiplayer",
    folderNames: ["3DO", "PANASONIC"],
    extensions: [".bin", ".chd", ".cue", ".iso", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Adventure Game Studio Game Engine",
    folderNames: ["ags"],
    extensions: [".app", ".sh"],
    icon: "",
  },
  {
    name: "Commodore Amiga",
    folderNames: ["amiga", "AMIGA"],
    extensions: [
      ".adf",
      ".adz",
      ".ccd",
      ".chd",
      ".cue",
      ".dms",
      ".fdi",
      ".hdf",
      ".hdz",
      ".ipf",
      ".rp9",
      ".iso",
      ".lha",
      ".m3u",
      ".mds",
      ".nrg",
      ".uae",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Commodore Amiga 1200",
    folderNames: ["amiga1200", "AMIGA"],
    extensions: [
      ".adf",
      ".adz",
      ".ccd",
      ".chd",
      ".cue",
      ".dms",
      ".fdi",
      ".hdf",
      ".hdz",
      ".ipf",
      ".rp9",
      ".iso",
      ".lha",
      ".m3u",
      ".mds",
      ".nrg",
      ".uae",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Commodore Amiga 600",
    folderNames: ["amiga600", "AMIGA"],
    extensions: [
      ".adf",
      ".adz",
      ".ccd",
      ".chd",
      ".cue",
      ".dms",
      ".fdi",
      ".hdf",
      ".hdz",
      ".ipf",
      ".rp9",
      ".iso",
      ".lha",
      ".m3u",
      ".mds",
      ".nrg",
      ".uae",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Commodore Amiga CD32",
    folderNames: ["amigacd32", "AMIGACD"],
    extensions: [
      ".adf",
      ".adz",
      ".ccd",
      ".chd",
      ".cue",
      ".dms",
      ".fdi",
      ".hdf",
      ".hdz",
      ".ipf",
      ".rp9",
      ".iso",
      ".lha",
      ".m3u",
      ".mds",
      ".nrg",
      ".uae",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Amstrad CPC",
    folderNames: ["amstradcpc", "CPC"],
    extensions: [
      ".cdt",
      ".cpr",
      ".dsk",
      ".kcr",
      ".m3u",
      ".sna",
      ".tap",
      ".voc",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Google Android",
    folderNames: ["android"],
    extensions: ["apk"],
    icon: "",
  },
  {
    name: "Apple II",
    folderNames: ["apple2"],
    extensions: [".do", ".dsk", ".nib", ".po"],
    icon: "",
  },
  {
    name: "Apple IIGS",
    folderNames: ["apple2gs"],
    extensions: [".2mg"],
    icon: "",
  },
  {
    name: "Arcade",
    folderNames: [
      "arcade",
      "ARCADE",
      "Arcade (FBNEO)",
      "Vertical Arcade (VARCADE)",
    ],
    extensions: [".app", ".cmd", ".sh", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Emerson Arcadia 2001",
    folderNames: ["arcadia"],
    extensions: [".bin", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Arduboy Miniature Game System",
    folderNames: ["arduboy"],
    extensions: [".hex", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Bally Astrocade",
    folderNames: ["astrocde"],
    extensions: [".7z", ".zip"],
    icon: "",
  },
  {
    name: "Atari 2600",
    folderNames: ["atari2600", "ATARI"],
    extensions: [".a26", ".bin", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Atari 5200",
    folderNames: ["atari5200", "FIFTYTWOHUNDRED"],
    extensions: [
      ".a52",
      ".atr",
      ".atx",
      ".bin",
      ".car",
      ".cas",
      ".cdm",
      ".rom",
      ".xex",
      ".xfd",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Atari 7800 ProSystem",
    folderNames: ["atari7800", "SEVENTYEIGHTHUNDRED"],
    extensions: [".a78", ".bin", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Atari 800",
    folderNames: ["atari800", "EIGHTHUNDRED"],
    extensions: [
      ".a52",
      ".atr",
      ".atx",
      ".bin",
      ".car",
      ".cas",
      ".cdm",
      ".rom",
      ".xex",
      ".xfd",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Atari Jaguar",
    folderNames: ["atarijaguar", "JAGUAR"],
    extensions: [
      ".abs",
      ".bin",
      ".cdi",
      ".cof",
      ".cue",
      ".j64",
      ".jag",
      ".prg",
      ".rom",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Atari Jaguar CD",
    folderNames: ["atarijaguarcd"],
    extensions: [".7z", ".zip"],
    icon: "",
  },
  {
    name: "Atari Lynx",
    folderNames: ["atarilynx", "LYNX"],
    extensions: [".lnx", ".o", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Atari ST",
    folderNames: ["atarist", "ATARIST"],
    extensions: [".st", ".msa", ".stx", ".dim", ".ipf", ".m3u", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Atari XE",
    folderNames: ["atarixe"],
    extensions: [
      ".a52",
      ".atr",
      ".atx",
      ".bin",
      ".cas",
      ".cdm",
      ".xex",
      ".xfd",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Sammy Corporation Atomiswave",
    folderNames: ["atomiswave"],
    extensions: [
      ".bin",
      ".cdi",
      ".cue",
      ".dat",
      ".elf",
      ".gdi",
      ".iso",
      ".lst",
      ".m3u",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Acorn Computers BBC Micro",
    folderNames: ["bbcmicro"],
    extensions: [".dsd", ".img", ".ssd", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Commodore 64",
    folderNames: ["c64", "COMMODORE"],
    extensions: [
      ".bin",
      ".cmd",
      ".crt",
      ".d2m",
      ".d4m",
      ".d64",
      ".d6z",
      ".d71",
      ".d7z",
      ".d80",
      ".d81",
      ".d82",
      ".d8z",
      ".g41",
      ".g4z",
      ".g64",
      ".g6z",
      ".gz",
      ".lnx",
      ".m3u",
      ".nbz",
      ".nib",
      ".p00",
      ".prg",
      ".t64",
      ".tap",
      ".vfl",
      ".vsf",
      ".x64",
      ".x6z",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Cave Story",
    folderNames: ["cavestory"],
    extensions: [".exe", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Philips CD-i",
    folderNames: ["cdimono1"],
    extensions: [".chd", ".cue", ".iso"],
    icon: "",
  },
  {
    name: "Commodore CDTV",
    folderNames: ["cdtv"],
    extensions: [
      ".ccd",
      ".chd",
      ".cue",
      ".iso",
      ".m3u",
      ".mds",
      ".nrg",
      ".rp9",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "ChaiLove Game Engine",
    folderNames: ["chailove"],
    extensions: [".chai", ".chailove", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Fairchild Channel F",
    folderNames: ["channelf", "FAIRCHILD"],
    extensions: [".bin", ".chf", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Tandy Color Computer",
    folderNames: ["coco"],
    extensions: [".cas", ".ccc", ".dsk", ".rom"],
    icon: "",
  },
  {
    name: "Coleco ColecoVision",
    folderNames: ["colecovision", "COLECO"],
    extensions: [
      ".bin",
      ".cas",
      ".col",
      ".cv",
      ".dsk",
      ".m3u",
      ".mx1",
      ".mx2",
      ".ri",
      ".rom",
      ".sc",
      ".sg",
      ".7z",
      ".zip",
    ],
    icon: "",
  },
  {
    name: "Capcom Play System",
    folderNames: ["cps", "CPS"],
    extensions: [".7z", ".zip"],
    icon: "",
  },
  {
    name: "Capcom Play System I",
    folderNames: ["cps1", "CPS1"],
    extensions: [".7z", ".zip"],
    icon: "",
  },
  {
    name: "Capcom Play System II",
    folderNames: ["cps2", "CPS2"],
    extensions: [".7z", ".zip"],
    icon: "",
  },
  {
    name: "Capcom Play System III",
    folderNames: ["cps3", "CPS3"],
    extensions: [".7z", ".zip"],
    icon: "",
  },
  {
    name: "VTech CreatiVision",
    folderNames: ["crvision"],
    icon: "",
  },
  {
    name: "Daphne Arcade LaserDisc Emulator",
    folderNames: ["cps3", "DAPHNE"],
    icon: "",
  },
  {
    name: "Doom",
    folderNames: ["doom"],
    icon: "",
  },
  {
    name: "DOS (PC)",
    folderNames: ["dos", "DOS"],
    icon: "",
  },
  {
    name: "Dragon Data Dragon 32",
    folderNames: ["dragon32"],
    icon: "",
  },
  {
    name: "Sega Dreamcast",
    folderNames: ["dreamcast", "Sega Dreamcast (DC)"],
    icon: "",
  },
  {
    name: "EasyRPG Game Engine",
    folderNames: ["easyrpg", "EASYRPG"],
    icon: "",
  },
  {
    name: "NES",
    folderNames: ["nes", "famicon", "FC", "Nintendo Entertainment System (FC)"],
    extensions: [".fds", ".nes", ".unf", ".unif", ".7z", ".zip"],
    icon: "",
  },
  {
    name: "Sony Playstation 2",
    folderNames: ["ps2"],
    icon: "",
  },
  {
    name: "Sony Playstation 3",
    folderNames: ["ps3"],
    icon: "",
  },
  {
    name: "Sony Playstation 4",
    folderNames: ["ps4"],
    icon: "",
  },
  {
    name: "Sony Playstation Portable",
    folderNames: ["psp", "PlayStation Portable (PSP)"],
    icon: "",
  },
  {
    name: "Sony Playstation Vita",
    folderNames: ["psvita"],
    icon: "",
  },
  {
    name: "Sony Playstation",
    folderNames: ["psx", "PS", "Sony PlayStation (PS)", "PS1"],
    icon: "",
  },
  {
    name: "Sega Saturn",
    folderNames: ["saturn", "saturnjs"],
    icon: "",
  },
  {
    name: "Sega 32X",
    folderNames: ["sega32x", "sega32xjp", "sega32xna", "THIRTYTWOX"],
    icon: "",
  },
  {
    name: "Sega Genesis/Mega Drive",
    folderNames: [
      "genesis",
      "megadrive",
      "megadrivejp",
      "MD",
      "Sega Genesis (MD)",
    ],
    icon: "",
  },
  {
    name: "Sega CD",
    folderNames: ["megacd", "megacdjp", "segacd"],
    icon: "",
  },
  {
    name: "Sega SG-1000",
    folderNames: ["sg-1000", "SEGASGONE"],
    icon: "",
  },
  {
    name: "FinalBurn Alpha",
    folderNames: ["fba", "ARCADE"],
    icon: "",
  },
  {
    name: "FinalBurn Neo",
    folderNames: ["fbneo", "ARCADE"],
    icon: "",
  },
  {
    name: "Nintendo Famicom Disk System",
    folderNames: ["fds", "FDS"],
    icon: "",
  },
  {
    name: "Fujitsu FM Towns",
    folderNames: ["fmtowns"],
    icon: "",
  },
  {
    name: "Future Pinball",
    folderNames: ["fpinball"],
    icon: "",
  },
  {
    name: "Game & Watch",
    folderNames: ["gameandwatch", "GW"],
    icon: "",
  },
  {
    name: "Hartung Game Master",
    folderNames: ["gmaster"],
    icon: "",
  },
  {
    name: "Amstrad GX4000",
    folderNames: ["gx4000"],
    icon: "",
  },
  {
    name: "LCD Handheld Games",
    folderNames: ["lcdgames"],
    icon: "",
  },
  {
    name: "LowRes NX Fantasy Console",
    folderNames: ["lowresnx"],
    icon: "",
  },
  {
    name: "Lutro Game Engine",
    folderNames: ["lutro"],
    icon: "",
  },
  {
    name: "Multiple Arcade Machine Emulator",
    folderNames: ["mame", "ARCADE"],
    icon: "",
  },
  {
    name: "AdvanceMAME",
    folderNames: ["mame-advmame", "ARCADE"],
    icon: "",
  },
  {
    name: "MAME4ALL",
    folderNames: ["mame-mame4all", "ARCADE"],
    icon: "",
  },
  {
    name: "Multi Emulator Super System",
    folderNames: ["mess"],
    icon: "",
  },
  {
    name: "Nintendo 3DS",
    folderNames: ["n3ds"],
    icon: "",
  },
  {
    name: "Nintendo DS",
    folderNames: ["ds", "DS", "Nintendo DS (NDS)"],
    icon: "",
  },
  {
    name: "Nintendo 64",
    folderNames: ["n64", "Nintendo 64 (N64)"],
    icon: "",
  },
  {
    name: "Nintendo 64DD",
    folderNames: ["n64dd"],
    icon: "",
  },
  {
    name: "Nintendo Wii",
    folderNames: ["wii"],
    icon: "",
  },
  {
    name: "Nintendo Wii U",
    folderNames: ["wiiu"],
    icon: "",
  },
  {
    name: "Microsoft Xbox",
    folderNames: ["xbox"],
    icon: "",
  },
  {
    name: "Microsoft Xbox 360",
    folderNames: ["xbox360"],
    icon: "",
  },
  {
    name: "Sinclair ZX81",
    folderNames: ["zx81", "ZXEIGHTYONE"],
    icon: "",
  },
  {
    name: "Sinclair ZX Spectrum",
    folderNames: ["zxspectrum", "ZXS"],
    icon: "",
  },
  {
    name: "Sinclair ZX Spectrum Next",
    folderNames: ["zxnext"],
    icon: "",
  },
  {
    name: "Infocom Z-machine",
    folderNames: ["zmachine"],
    icon: "",
  },
  {
    name: "Sharp X68000",
    folderNames: ["x68000", "X68000"],
    icon: "",
  },
  {
    name: "WASM-4 Fantasy Console",
    folderNames: ["wasm4"],
    icon: "",
  },
  {
    name: "VTech V.Smile",
    folderNames: ["vsmile"],
    icon: "",
  },
  {
    name: "Visual Pinball",
    folderNames: ["vpinball"],
    icon: "",
  },
  {
    name: "Solarus Game Engine",
    folderNames: ["solarus"],
    icon: "",
  },
  {
    name: "Spectravideo",
    folderNames: ["spectravideo"],
    icon: "",
  },
  {
    name: "Stratagus Game Engine",
    folderNames: ["stratagus"],
    icon: "",
  },
  {
    name: "Bandai SuFami Turbo",
    folderNames: ["sufami"],
    icon: "",
  },
  {
    name: "Epoch Super Cassette Vision",
    folderNames: ["scv"],
    icon: "",
  },
  {
    name: "ScummVM Game Engine",
    folderNames: ["scummvm", "SCUMMVM"],
    icon: "",
  },
  {
    name: "Symbian",
    folderNames: ["symbian"],
    icon: "",
  },
  {
    name: "Tano Dragon",
    folderNames: ["tanodragon"],
    icon: "",
  },
  {
    name: "MGT SAM Coupé",
    folderNames: ["samcoupe"],
    icon: "",
  },
  {
    name: "Casio PV-1000",
    folderNames: ["pv1000"],
    icon: "",
  },
  {
    name: "IBM PC",
    folderNames: ["pc"],
    icon: "",
  },
  {
    name: "Palm OS",
    folderNames: ["palm"],
    icon: "",
  },
  {
    name: "Tangerine Computer Systems Oric",
    folderNames: ["oric"],
    icon: "",
  },
  {
    name: "OpenBOR Game Engine",
    folderNames: ["openbor", "OPENBOR"],
    icon: "",
  },
  {
    name: "Sharp X1",
    folderNames: ["x1", "XONE"],
    icon: "",
  },
  {
    name: "Bandai WonderSwan",
    folderNames: ["wonderswan", "WS"],
    icon: "",
  },
  {
    name: "Bandai WonderSwan Color",
    folderNames: ["wonderswancolor", "WS"],
    icon: "",
  },
  {
    name: "Nintendo Virtual Boy",
    folderNames: ["virtualboy", "VB", "Virtual Boy (VB)"],
    icon: "",
  },
  {
    name: "Philips Videopac G7000",
    folderNames: ["videopac", "ODYSSEY"],
    icon: "",
  },
  {
    name: "Commodore VIC-20",
    folderNames: ["vic20", "COMMODORE"],
    icon: "",
  },
  {
    name: "Smith Engineering Vectrex",
    folderNames: ["vectrex", "VECTREX"],
    icon: "",
  },
  {
    name: "Uzebox Open Source Console",
    folderNames: ["uzebox", "UZEBOX"],
    icon: "",
  },
  {
    name: "Tandy TRS-80",
    folderNames: ["trs-80"],
    icon: "",
  },
  {
    name: "Thomson TO8",
    folderNames: ["to8"],
    icon: "",
  },
  {
    name: "TIC-80 Game Engine",
    folderNames: ["tic80", "TIC"],
    icon: "",
  },
  {
    name: "Texas Instruments TI-99",
    folderNames: ["ti99"],
    icon: "",
  },
  {
    name: "Nintendo Switch",
    folderNames: ["switch"],
    icon: "",
  },
  {
    name: "Super Nintendo",
    folderNames: [
      "snes",
      "snesna",
      "sfc",
      "SFC",
      "Super Nintendo Entertainment System (SFC)",
      "Super Nintendo Entertainment System (SUPA)",
    ],
    icon: "",
  },
  {
    name: "Watara Supervision",
    folderNames: ["supervision", "SUPERVISION"],
    icon: "",
  },
  {
    name: "NEC SuperGrafx",
    folderNames: ["supergrafx", "SGFX"],
    icon: "",
  },
  {
    name: "NEC PC-8800 Series",
    folderNames: ["pc88"],
    icon: "",
  },
  {
    name: "NEC PC-9800 Series",
    folderNames: ["pc98"],
    icon: "",
  },
  {
    name: "PICO-8 Fantasy Console",
    folderNames: ["pico8", "PICO", "Pico-8 (P8)"],
    icon: "",
  },
  {
    name: "Nintendo Pokémon Mini",
    folderNames: ["pokemini", "POKE", "Pokémon mini (PKM)"],
    icon: "",
  },
  {
    name: "Tiger Electronics Game.com",
    folderNames: ["gamecom"],
    icon: "",
  },
  {
    name: "Sega Game Gear",
    folderNames: ["gamegear", "GG", "Sega Game Gear (GG)"],
    icon: "",
  },
  {
    name: "Nintendo Game Boy",
    folderNames: ["gb", "GB", "Game Boy (GB)"],
    icon: "",
  },
  {
    name: "Nintendo Game Boy Advance",
    folderNames: [
      "gba",
      "GBA",
      "Game Boy Advance (GBA)",
      "Game Boy Advance (MGBA)",
    ],
    icon: "",
  },
  {
    name: "Nintendo Game Boy Color",
    folderNames: ["gbc", "GBC", "Game Boy Color (GBC)"],
    icon: "",
  },
  {
    name: "Nintendo GameCube",
    folderNames: ["gc"],
    icon: "",
  },
  {
    name: "Mattel Electronics Intellivision",
    folderNames: ["intellivision", "INTELLIVISION"],
    icon: "",
  },
  {
    name: "Sega Master System",
    folderNames: ["mastersystem", "MS", "Sega Master System (SMS)", "SMS"],
    icon: "",
  },
  {
    name: "Sega Model 2",
    folderNames: ["model2"],
    icon: "",
  },
  {
    name: "Sega Model 3",
    folderNames: ["model3"],
    icon: "",
  },
  {
    name: "Thomson MO/TO Series",
    folderNames: ["moto"],
    icon: "",
  },
  {
    name: "MSX",
    folderNames: ["msx", "MSX"],
    icon: "",
  },
  {
    name: "MSX1",
    folderNames: ["msx1", "MSX"],
    icon: "",
  },
  {
    name: "MSX2",
    folderNames: ["msx2", "MSX"],
    icon: "",
  },
  {
    name: "Creatronic Mega Duck",
    folderNames: ["megaduck", "MEGADUCK"],
    icon: "",
  },
  {
    name: "Apple Macintosh",
    folderNames: ["macintosh"],
    icon: "",
  },
  {
    name: "MSX Turbo R",
    folderNames: ["msxturbor"],
    icon: "",
  },
  {
    name: "M.U.G.E.N Game Engine",
    folderNames: ["mugen"],
    icon: "",
  },
  {
    name: "Othello Multivision",
    folderNames: ["multivision"],
    icon: "",
  },
  {
    name: "NEC TurboGrafx-16",
    folderNames: [
      "tg16",
      "pcengine",
      "PCE",
      "/Volumes/FLIP/Roms/TurboGrafx-16 (PCE)",
    ],
    icon: "",
  },
  {
    name: "NEC TurboGrafx CD",
    folderNames: ["pcenginecd", "PCECD", "tg-cd"],
    icon: "",
  },
  {
    name: "Sega NAOMI",
    folderNames: ["naomi"],
    icon: "",
  },
  {
    name: "Sega NAOMI CD-ROM",
    folderNames: ["naomigd"],
    icon: "",
  },
  {
    name: "SNK Neo Geo",
    folderNames: ["neogeo", "NEOGEO"],
    icon: "",
  },
  {
    name: "SNK Neo Geo CD",
    folderNames: ["neogeocd", "neogeocdjp", "NEOCD"],
    icon: "",
  },
  {
    name: "SNK Neo Geo Pocket",
    folderNames: ["ngp", "NGP"],
    icon: "",
  },
  {
    name: "SNK Neo Geo Pocket Color",
    folderNames: ["ngpc", "NGP", "Neo Geo Pocket Color (NGPC)"],
    icon: "",
  },
  {
    name: "Magnavox Odyssey2",
    folderNames: ["odyssey2", "ODYSSEY"],
    icon: "",
  },
  {
    name: "NEC PC-FX",
    folderNames: ["pcfx", "PCFX"],
    icon: "",
  },
  {
    name: "Nintendo Satellaview",
    folderNames: ["satellaview", "SATELLAVIEW"],
    icon: "",
  },
  {
    name: "Nintendo Super Game Boy",
    folderNames: ["sgb", "SGB", "Super Game Boy (SGB)"],
    icon: "",
  },
];
